### PR TITLE
Move Throttler + FrequencyCalculator, add PausableLoopingThread (to be renamed)

### PR DESCRIPTION
**Pull request by TomaszTB**

### CODE REVIEW

**Comment by TomaszTB** [comment]
Not sure what to do about `ThrottlerAndFrequencyCounterTest`. Should we move `FrequencyCalculator` to here too?

**Comment by TomaszTB** [comment]
Perhaps `Throttler` should go in commons/time instead of commons/thread?

**Comment by calvertdw** [comment]
> Not sure what to do about `ThrottlerAndFrequencyCounterTest`. Should we move `FrequencyCalculator` to here too?

Yes

**Review by ds58 — APPROVED** [review]

**Comment by TomaszTB** [comment]
Making PR with history preserved

**Pull request closed without merging**
